openapi: 3.2.0
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: LogicMonitor is a SaaS-based performance monitoring platform that provides full visibility into complex, hybrid infrastructures, offering granular performance monitoring and actionable data and insights.
  title: LogicMonitor REST DNS Mappings API
  version: 2.0.0
servers:
- url: /santaba/rest
tags:
- name: DNSMappings
paths:
  /setting/dnsmappings:
    post:
      summary: import DNS mapping via CSV
      security:
      - LMv1: []
      description: ''
      operationId: importDNSMapping
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
      - DNSMappings
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: the csv mapping to be uploaded
                  format: binary
              required:
              - file
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errorMessage:
          description: The error message
          readOnly: true
          type: string
        errorCode:
          format: int32
          description: The error code
          readOnly: true
          type: integer
        errorDetail:
          description: The error detail
          readOnly: true
          type: object
  securitySchemes:
    LMv1:
      in: header
      name: Authorization
      type: apiKey
externalDocs:
  description: LogicMonitor Support Docs
  url: https://www.logicmonitor.com/support/rest-api-developers-guide/
