openapi: 3.2.0
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: LogicMonitor is a SaaS-based performance monitoring platform that provides full visibility into complex, hybrid infrastructures, offering granular performance monitoring and actionable data and insights.
  title: LogicMonitor REST Job Monitor API
  version: 3.0.0
servers:
- url: /santaba/rest
tags:
- name: JobMonitor
paths:
  /setting/batchjobs/importjson:
    post:
      summary: Import batch JobMonitor via json
      security:
      - LMv1: []
      x-minimum-permissions:
        Modules ->  All Installed modules: Manage
        Modules -> Access Groups: Manage
      description: Import a JobMonitor using json data
      operationId: importJobMonitorJson
      responses:
        '200':
          description: Successfully imported the JobMonitor via Json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJob'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - in: query
        name: handleConflict
        schema:
          type: string
      - in: query
        name: fieldsToPreserve
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      tags:
      - JobMonitor
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
  /setting/batchjobs/{id}:
    patch:
      summary: Update JobMonitor
      security:
      - LMv1: []
      x-minimum-permissions:
        Modules ->  All Installed modules: Manage
      description: Update an existing JobMonitor by its ID
      operationId: patchJobMonitor
      responses:
        '200':
          description: Successfully updated the JobMonitor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJob'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
      - in: query
        name: reason
        schema:
          type: string
      tags:
      - JobMonitor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchJob'
    get:
      summary: Get JobMonitor by ID
      security:
      - LMv1: []
      x-minimum-permissions:
        Modules ->  Access Group: View
      description: Retrieve a specific JobMonitor using its ID
      operationId: getJobMonitorById
      responses:
        '200':
          description: Successfully retrieved the JobMonitor by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJob'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
      - in: query
        name: format
        schema:
          type: string
      tags:
      - JobMonitor
    delete:
      summary: Delete JobMonitor
      security:
      - LMv1: []
      x-minimum-permissions:
        Modules ->  All Installed modules: Manage
      description: Delete a specific JobMonitor by its ID
      operationId: deleteJobMonitor
      responses:
        '200':
          description: Successfully deleted the JobMonitor
          content:
            application/json:
              schema:
                type: object
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
      tags:
      - JobMonitor
    put:
      summary: Update JobMonitor
      security:
      - LMv1: []
      x-minimum-permissions:
        Modules ->  All Installed modules: Manage
      description: Update an existing JobMonitor by its ID
      operationId: updateJobMonitor
      responses:
        '200':
          description: Successfully updated the JobMonitor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJob'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
      - in: query
        name: reason
        schema:
          type: string
      tags:
      - JobMonitor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchJob'
  /setting/batchjobs/importxml:
    post:
      summary: Import batch job via XML
      security:
      - LMv1: []
      x-minimum-permissions:
        Modules ->  All Installed modules: Manage
      description: Import a batch job using XML data
      operationId: importBatchJob
      responses:
        '200':
          description: Successfully imported the batch job via XML
          content:
            application/json:
              schema:
                type: object
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
      - JobMonitor
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
  /setting/batchjobs:
    post:
      summary: Add JobMonitor
      security:
      - LMv1: []
      x-minimum-permissions:
        Modules ->  All Installed modules: Manage
      description: Create a new JobMonitor
      operationId: addJobMonitor
      responses:
        '200':
          description: Successfully added the JobMonitor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJob'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
      - JobMonitor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchJob'
    get:
      summary: Get JobMonitor List
      security:
      - LMv1: []
      x-minimum-permissions:
        Modules ->  All Installed modules: View
      description: Retrieve a paginated list of Job Monitors
      operationId: getJobMonitorList
      responses:
        '200':
          description: Successfully retrieved the JobMonitor list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchJobPaginationResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - in: query
        name: format
        schema:
          type: string
      tags:
      - JobMonitor
components:
  schemas:
    BatchJobPaginationResponse:
      type: object
      properties:
        total:
          format: int32
          readOnly: true
          type: integer
        searchId:
          readOnly: true
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/BatchJob'
    BatchJob:
      type: object
      required:
      - alertBody
      - alertEffectiveIval
      - alertLevel
      - alertSubject
      - cronSchedule
      - cronTimeZone
      - name
      properties:
        activeMonitoring:
          description: Whether to enable active monitoring of job start
          type: boolean
        accessGroups:
          description: Module's access groups
          type: array
          items:
            $ref: '#/components/schemas/AccessGroup'
        alertLevel:
          description: alert level if job doesn't start on time, effective if activeMonitoring true
          type: string
          enum:
          - warn
          - error
          - critical
        description:
          description: The description for the LMModule
          type: string
        appliesTo:
          description: The Applies To for the LMModule
          type: string
        technology:
          description: The Technical Notes for the LMModule
          type: string
        lineageId:
          description: The lineageId the LMModule belongs to
          readOnly: true
          type: string
        cronSchedule:
          description: Cron schedule expression, only the latter 5 ,effective if activeMonitoring true
          type: string
        tags:
          description: The Tags for the LMModule
          type: string
        installationMetadata:
          description: The local module's IntegrationMetadata, readable for troubleshooting purposes
          readOnly: true
          $ref: '#/components/schemas/IntegrationMetadata'
        cronTimeZone:
          description: Cron timezone, effective if activeMonitoring true
          type: string
        alertBody:
          description: Alert message body
          type: string
        startMrtie:
          format: int32
          description: Max Relative Time Interval Error, effective if activeMonitoring true
          type: integer
        originRegistryId:
          description: The Registry ID of the Exchange Integration this module is based from, including this field will set this as the module's import base and mark the ID's version as audited
          type: string
        checksum:
          description: The metadata checksum for the LMModule content
          readOnly: true
          type: string
        name:
          description: JobMonitor name
          type: string
        alertSubject:
          description: Alert message subject
          type: string
        id:
          format: int32
          description: The ID of the LMModule
          readOnly: true
          type: integer
        accessGroupIds:
          uniqueItems: true
          description: The Access Groups Id's
          type: array
          items:
            format: int32
            description: The Access Groups Id's
            type: integer
          example: 1, 2, 3
        isInUse:
          description: Whether the LM module is currently in use
          readOnly: true
          type: boolean
        longestRunTimeInMinute:
          format: int32
          description: Max job run time in minutes
          type: integer
        alertEffectiveIval:
          format: int32
          description: JobMonitor alert effective interval in minutes
          type: integer
          example: 60
        group:
          description: The group the LMModule is in
          type: string
    ErrorResponse:
      type: object
      properties:
        errorMessage:
          description: The error message
          readOnly: true
          type: string
        errorCode:
          format: int32
          description: The error code
          readOnly: true
          type: integer
        errorDetail:
          description: The error detail
          readOnly: true
          type: object
    AccessGroup:
      description: Module's access groups
      type: object
      required:
      - name
      properties:
        createdBy:
          description: User who created access group
          readOnly: true
          type: string
        name:
          description: The name of the access group
          type: string
          example: LinuxGroup
        tenantId:
          description: Tenancy details
          type: string
        description:
          description: Description about access group
          type: string
        id:
          format: int32
          description: The id of the access group
          readOnly: true
          type: integer
        updatedOn:
          format: int64
          description: Time when access group updated
          readOnly: true
          type: integer
        createdOn:
          format: int64
          description: Time when access group created
          readOnly: true
          type: integer
    IntegrationMetadata:
      description: The local module's IntegrationMetadata, readable for troubleshooting purposes
      readOnly: true
      type: object
      properties:
        targetLastPublishedId:
          description: Specifies the target last published Id
          readOnly: true
          type: string
        targetLastPublishedChecksum:
          description: The metadata checksum for the target last published LMModule content
          readOnly: true
          type: string
        targetLastPublishedVersion:
          description: Specifies the target last published version
          readOnly: true
          type: string
        originChecksum:
          description: The metadata checksum for the LMModule content
          readOnly: true
          type: string
        originAuthorNamespace:
          description: Specifies the origin Author companies namespace
          readOnly: true
          type: string
        originLocator:
          description: Specifies the origin version locator
          readOnly: true
          type: string
        isChangedFromOrigin:
          description: Specifies if the Applies To function is changed from origin or not
          readOnly: true
          type: boolean
        auditedRegistryId:
          description: Specifies the audited registry Id
          readOnly: true
          type: string
        targetLineageId:
          description: Specifies the target lineage Id
          readOnly: true
          type: string
        logicModuleType:
          description: 'The values can be DataSources | EventSources | PropertySources | ConfigSources | LogSources | TopologySources | Jobmonitors | AppliesTo Functions | SNMP SysOID Maps

            The type of LogicModule'
          readOnly: true
          type: string
          enum:
          - DATASOURCE
          - EVENTSOURCE
          - CONFIGSOURCE
          - PROPERTYSOURCE
          - DIAGNOSTICSOURCE
          - REMEDIATIONSOURCE
          - TOPOLOGYSOURCE
          - JOBMONITOR
          - APPLIESTO_FUNCTION
          - SNMP_SYSOID_MAP
          - LOGSOURCE
        isChangedFromTargetLastPublished:
          description: Specifies if the Applies To function is changed from target last published or not
          readOnly: true
          type: boolean
        originLineageId:
          description: The origin lineage Id of the LMmodule
          readOnly: true
          type: string
        originAuthorCompanyUUID:
          description: Specifies the origin Author companies unique Id
          readOnly: true
          type: string
        localModuleId:
          format: int32
          description: The LocalModule Id
          readOnly: true
          type: integer
        originRegistryId:
          description: The Registry ID of the Exchange Integration this module is based from
          readOnly: true
          type: string
        originVersion:
          description: Specifies the origin version
          readOnly: true
          type: string
        auditedVersion:
          description: Specifies the audited registry version
          readOnly: true
          type: string
        originName:
          description: Specifies the origin module name
          readOnly: true
          type: string
  securitySchemes:
    LMv1:
      in: header
      name: Authorization
      type: apiKey
externalDocs:
  description: LogicMonitor Support Docs
  url: https://www.logicmonitor.com/support/rest-api-developers-guide/
